# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4d9600ee49f617d6164ef68afae63686e6601cdd7bf29d30343a5899c1f48f9bc86fe255c6e961f222910cd82edceb3ff960c4fadc2d358ca26dbc9d7c291b1

test:
  secret_key_base: 1b058be7b2fad2e325a1214a514a9d3fa1e91a0cb64dc7a25244a685a723e4fb3bc46f4a0a03ee046f6068d81d1016ff6e2a9edf9e04e2895d934171e7b650f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
